-- This file is used to seed initial data for development purposes

-- Sample assets (will only be used if data doesn't exist already)
INSERT INTO assets (symbol, name, asset_type, current_price, price_updated_at, created_at, updated_at)
VALUES
    ('AAPL', 'Apple Inc.', 'STOCK', 175.25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MSFT', 'Microsoft Corporation', 'STOCK', 330.50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('AMZN', 'Amazon.com Inc.', 'STOCK', 130.75, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('GOOGL', 'Alphabet Inc.', 'STOCK', 140.32, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TSLA', 'Tesla Inc.', 'STOCK', 250.98, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('BTC', 'Bitcoin', 'CRYPTO', 42500.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ETH', 'Ethereum', 'CRYPTO', 2250.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('VWRL.L', 'Vanguard FTSE All-World UCITS ETF', 'ETF', 105.24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('EIMI.L', 'iShares Core MSCI Emerging Markets IMI UCITS ETF', 'ETF', 28.75, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('IGIL.L', 'iShares Global Inflation Linked Govt Bond UCITS ETF', 'BOND', 5.42, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('GOLD', 'Gold', 'COMMODITY', 1925.60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('EUR', 'Euro', 'CASH', 1.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('REAL_DE', 'German Real Estate', 'REAL_ESTATE', 100000.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (symbol) DO NOTHING;
